syntax = "proto3";

package com.coen6731.chat;

option java_multiple_files = true;
option java_package = "com.coen6731.chat";
option java_outer_classname = "ChatProto";

service MessagingService {
  // A bidirectional streaming RPC.
  // Both the client and server can send a stream of messages to each other.
  // 'stream ClientEvent' means the client sends a stream of ClientEvent messages.
  // 'returns (stream ServerEvent)' means the server responds with a stream of ServerEvent messages.
  rpc Chat(stream ClientEvent) returns (stream ServerEvent);
}

// client -> server
message ClientEvent {
  oneof payload {
    LoginUser loginUser = 1; 
    RegisterUser registerUser = 2; 
    SendMessage sendMessage = 3;
    HeartbeatPing heartbeatPing = 4;
    Catchup catchup = 5;
  }
}

// server -> client
message ServerEvent {
  oneof payload {
    ChatMessage chatMessage = 1; // message from server to client.
    ServerError serverError = 2;
    CatchupComplete catchupComplete = 3;
    HeartbeatPong heartbeatPong = 4;
  }
}

// ------------------------------------------------------------------------------------------------
// client messages

// notify server this user is available, add to connection registry.
message LoginUser {
  string userId = 1; // The user's ID.
}

// sned new user information to server, add to database.
message RegisterUser {
  string userId = 1; // The user's ID.
  string userName = 2; // The user's name.
}

message SendMessage {
  string toUserId = 1; // The recipient's user ID.
  string text = 2;     // The content of the message.
  string clientMsgId = 3; // A client-generated ID for tracking/deduplication.
}

// Heartbeat message to keep the connection alive.
message HeartbeatPing {
  int64 ts = 1; // Timestamp of the heartbeat.
}

message Catchup {
  string userId = 1; // my user id
  int64 lastSyncSequenceId = 2; // the last sequence id i have received
}
  
// ------------------------------------------------------------------------------------------------
// server messages
message ChatMessage {
  string fromUserId = 1; // The sender's user ID.
  string text = 2;       // The message content.
  string serverMsgId = 3; // Unique ID assigned by the server.
  int64 ts = 4;          // Timestamp when the message was processed by the server.
}

message ServerError {
  string code = 1;   // Error code (e.g., "USER_OFFLINE").
  string reason = 2; // Human-readable error message.
}

message CatchupComplete {
  string userId = 1;
  int64 truthSequenceId = 2; 
}

message HeartbeatPong {
  int64 ts = 1; // Timestamp of the heartbeat.
}